version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependencias..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Construyendo proyecto..."
      - sam build
  deploy:
    commands:
      - echo "Desplegando aplicación en AWS..."
      - sam deploy --stack-name my-stack --region us-east-1 --capabilities CAPABILITY_IAM
artifacts:
  files:
    - template.yaml
    - packaged.yaml
