AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.getDataEva
      Runtime: python3.9
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)