version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::913045965320:user/aws-sam-cli-managed-prueba-pipeline-r-PipelineUser-U1W10SG1GVLD"
permissions_provider = "AWS IAM"

[prueba.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::913045965320:role/aws-sam-cli-managed-prueba-p-PipelineExecutionRole-1N8AXDF9WOPSK"
cloudformation_execution_role = "arn:aws:iam::913045965320:role/aws-sam-cli-managed-prueb-CloudFormationExecutionR-1QERYM6SQOJZ0"
artifacts_bucket = "pruebabucket12"
image_repository = ""
region = "us-east-1"
